#+Title: Database documentation
#+author: Vishnu Devarakonda
#+date: <2021-10-26 Tue>

* Progress
** TODO:
   1. Add tests.
   2. Need to add relationhips between the test users (buddies etc).
** Done:


* Database
** Files
   1. configureUsers.js: File creates a "users" collection with schema validation.
   2. configureBuddyRequests.js: File creates a "buddyRequests" collection with shema validation.
   3. buildCollections.sh: Shell script loads collections into the mongo.

** Collections
   1. users
      *** Fields
      1. userinfo - Object: Required
	 *** Fields
	 1. name - string: User's name. Required.
	 2. major - string: User's major. Required.
	 3. classes - array of strings. User's classes.
      2. userid - objectId: User's unique id.
      3. zoomid - string: User's zoom id. required.
      4. pastbuddies - array of objectIds: Id's of past buddies the user has interacted with.
      5. buddyrequests - array of objectIds: Contains objectids to current pending, accepton, and past requests for the user.
   2. buddyrequests
      *** Fields
      1. requestid - objectId: Unique request id.
      2. sender - objectId: ObjectId of user sending the request.
      3. receiver - objectId: ObjectId of user receiving the request.
      4. status - enum: ["Accepted", "Pending", "Cancelled"]. Determines state of request.
      5. dateslots - array of Timestamps: Contains timestamp indicating the date and time for study.
